import { Providers } from "./providers";
import { ColorSchemeScript } from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import Navbar from "@/components/Navbar";

import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";
import "./globals.css";

export const metadata = {
  title: "Cashful test",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <Providers>
          <Navbar />
          <Notifications position="bottom-right" />
          {children}
        </Providers>
      </body>
    </html>
  );
}
